#!/usr/bin/env bash
# /usr/lib/kport/use-helpers.sh
#
# USE flag resolution helpers for KPort pacscripts.
#
# Sourced by pacscript build() functions:
#   [[ -f /usr/lib/kport/use-helpers.sh ]] && source /usr/lib/kport/use-helpers.sh
#
# ── Flag resolution order (highest priority first) ───────────────────────────
#
#   1. Per-package overrides  ~/.config/kport/package.use
#   2. User global overrides  ~/.config/kport/use.conf
#   3. Hardware-derived flags ~/.config/kport/hardware.conf  (USE_* vars)
#   4. Package defaults       KUSE array declared in the pacscript
#
# ── Public API ────────────────────────────────────────────────────────────────
#
#   use_enabled <flag>              — returns 0 if flag is ON, 1 if OFF
#   use_disabled <flag>             — returns 0 if flag is OFF, 1 if ON
#   use_flag <flag> <if-on> <if-off> — prints if-on or if-off string
#   use_active_flags                — prints all active (ON) flag names
#   use_dump                        — prints full flag resolution table (debug)
#
# ── Config file formats ───────────────────────────────────────────────────────
#
#   ~/.config/kport/use.conf        — one flag per line, + or - prefix:
#     +wayland
#     -x11
#     +vulkan
#
#   ~/.config/kport/package.use     — package-scoped overrides:
#     kwin: +vulkan -x11
#     kf6-karchive: -test
#     *: -debug          (wildcard applies to all packages)
#
#   ~/.config/kport/hardware.conf   — generated by kport-detect, read-only here:
#     USE_VULKAN="on"
#     USE_VAAPI="on"
#     USE_OPENCL="off"
#     (USE_* variables map to lowercase flag names by stripping USE_ prefix)

# Guard against double-sourcing
[[ -n "${_KPORT_USE_HELPERS_LOADED:-}" ]] && return 0
_KPORT_USE_HELPERS_LOADED=1

# ── Internal state ────────────────────────────────────────────────────────────

# Associative array: flag_name → "on" | "off"
declare -gA _KPORT_FLAGS=()

# Track which source set each flag (for use_dump)
declare -gA _KPORT_FLAGS_SOURCE=()

# ── Config paths ──────────────────────────────────────────────────────────────

_KPORT_CONF_DIR="${KPORT_CONF_DIR:-${HOME}/.config/kport}"
_KPORT_HW_CONF="${_KPORT_CONF_DIR}/hardware.conf"
_KPORT_USE_CONF="${_KPORT_CONF_DIR}/use.conf"
_KPORT_PKG_USE="${_KPORT_CONF_DIR}/package.use"

# ── Internal helpers ──────────────────────────────────────────────────────────

# Normalise a flag name: lowercase, strip leading +/-
_kport_normalise_flag() {
  local f="${1#[+-]}"
  echo "${f,,}"
}

# Set a flag value, recording the source.
# Args: flag  value(on|off)  source-label
_kport_set_flag() {
  local flag="$1" val="$2" src="$3"
  _KPORT_FLAGS["$flag"]="$val"
  _KPORT_FLAGS_SOURCE["$flag"]="$src"
}

# Parse a +flag / -flag line and apply it.
# Args: flag-spec(+foo|-foo)  source-label
_kport_apply_spec() {
  local spec="$1" src="$2"
  local flag
  flag=$(_kport_normalise_flag "$spec")
  [[ -z "$flag" ]] && return
  if [[ "$spec" == -* ]]; then
    _kport_set_flag "$flag" "off" "$src"
  else
    _kport_set_flag "$flag" "on" "$src"
  fi
}

# ── Layer 4: KUSE package defaults ───────────────────────────────────────────

_kport_load_kuse() {
  # KUSE is declared in the pacscript as an array of "+flag" / "-flag" strings.
  # It must already be set in the calling environment.
  if [[ -n "${KUSE+x}" ]]; then
    for spec in "${KUSE[@]}"; do
      _kport_apply_spec "$spec" "KUSE-default"
    done
  fi
}

# ── Layer 3: hardware.conf ────────────────────────────────────────────────────

_kport_load_hardware() {
  [[ -f "$_KPORT_HW_CONF" ]] || return 0

  while IFS= read -r line; do
    # Strip comments and blank lines
    line="${line%%#*}"
    line="${line// /}"
    [[ -z "$line" ]] && continue

    # Match USE_FLAGNAME="on|off" or USE_FLAGNAME=on|off
    if [[ "$line" =~ ^USE_([A-Z0-9_]+)=\"?([^\"]+)\"?$ ]]; then
      local raw_name="${BASH_REMATCH[1]}"
      local val="${BASH_REMATCH[2],,}"   # lowercase
      # Convert USE_LLM_LOCAL → llm-local (underscores → hyphens, lowercase)
      local flag="${raw_name//_/-}"
      flag="${flag,,}"
      case "$val" in
        on|true|1|yes)   _kport_set_flag "$flag" "on"  "hardware.conf" ;;
        off|false|0|no)  _kport_set_flag "$flag" "off" "hardware.conf" ;;
        manual) ;;  # "manual" means don't auto-derive — leave current value
      esac
    fi
  done < "$_KPORT_HW_CONF"
}

# ── Layer 2: user global use.conf ─────────────────────────────────────────────

_kport_load_use_conf() {
  [[ -f "$_KPORT_USE_CONF" ]] || return 0

  while IFS= read -r line; do
    line="${line%%#*}"
    line="${line// /}"
    [[ -z "$line" ]] && continue
    _kport_apply_spec "$line" "use.conf"
  done < "$_KPORT_USE_CONF"
}

# ── Layer 1: per-package package.use ─────────────────────────────────────────

_kport_load_package_use() {
  [[ -f "$_KPORT_PKG_USE" ]] || return 0
  # pkgname must be set by the pacscript
  local pkg="${pkgname:-}"

  while IFS= read -r line; do
    line="${line%%#*}"
    [[ -z "${line// }" ]] && continue

    # Format: "pkgname: +flag -flag ..." or "*: +flag -flag ..."
    if [[ "$line" =~ ^([^:]+):[[:space:]]*(.+)$ ]]; then
      local entry_pkg="${BASH_REMATCH[1]// /}"
      local specs="${BASH_REMATCH[2]}"

      # Apply if wildcard or matches current package
      if [[ "$entry_pkg" == "*" || "$entry_pkg" == "$pkg" ]]; then
        for spec in $specs; do
          _kport_apply_spec "$spec" "package.use(${entry_pkg})"
        done
      fi
    fi
  done < "$_KPORT_PKG_USE"
}

# ── Initialise ────────────────────────────────────────────────────────────────

_kport_init() {
  _kport_load_kuse          # layer 4 — lowest priority
  _kport_load_hardware      # layer 3
  _kport_load_use_conf      # layer 2
  _kport_load_package_use   # layer 1 — highest priority
}

_kport_init

# ── Public API ────────────────────────────────────────────────────────────────

# use_enabled <flag>
# Returns 0 (true) if the flag is ON, 1 (false) if OFF or unknown.
use_enabled() {
  local flag="${1,,}"
  [[ "${_KPORT_FLAGS[$flag]:-off}" == "on" ]]
}

# use_disabled <flag>
# Returns 0 (true) if the flag is OFF or unknown, 1 (false) if ON.
use_disabled() {
  local flag="${1,,}"
  [[ "${_KPORT_FLAGS[$flag]:-off}" != "on" ]]
}

# use_flag <flag> <value-if-on> <value-if-off>
# Prints value-if-on or value-if-off depending on flag state.
# Typical use: -DWITH_WAYLAND=$(use_flag wayland ON OFF)
use_flag() {
  local flag="${1,,}"
  local if_on="$2"
  local if_off="$3"
  if use_enabled "$flag"; then
    echo "$if_on"
  else
    echo "$if_off"
  fi
}

# use_active_flags
# Prints the names of all flags currently set to ON, one per line.
use_active_flags() {
  local flag
  for flag in "${!_KPORT_FLAGS[@]}"; do
    [[ "${_KPORT_FLAGS[$flag]}" == "on" ]] && echo "$flag"
  done | sort
}

# use_dump
# Prints the full flag resolution table. Useful for debugging build issues.
use_dump() {
  echo "[kport/use-helpers] Flag resolution table for ${pkgname:-<unknown>}"
  echo "  Config dir : ${_KPORT_CONF_DIR}"
  echo "  hardware   : ${_KPORT_HW_CONF}"
  echo "  use.conf   : ${_KPORT_USE_CONF}"
  echo "  package.use: ${_KPORT_PKG_USE}"
  echo ""
  printf "  %-30s %-5s %s\n" "FLAG" "STATE" "SOURCE"
  printf "  %-30s %-5s %s\n" "----" "-----" "------"
  local flag
  for flag in $(echo "${!_KPORT_FLAGS[@]}" | tr ' ' '\n' | sort); do
    printf "  %-30s %-5s %s\n" \
      "$flag" \
      "${_KPORT_FLAGS[$flag]}" \
      "${_KPORT_FLAGS_SOURCE[$flag]:-?}"
  done
}
