#!/usr/bin/env bash
# kport source-build
#
# Builds one or more KDE packages from source using kdesrc-build.
# Acts as a KPort source backend: fetches KDE git sources, applies any
# local patches from the KPort package directory, and builds into a
# staging prefix that kport-binhost.sh can later archive.
#
# kdesrc-build docs: https://invent.kde.org/sdk/kdesrc-build
#
# Usage: kport source-build [options] [<package>...]
#
# Options:
#   --channel <c>      Target channel: stable|unstable|nightly (default: stable)
#   --prefix <dir>     Install prefix (default: /opt/kport/source-build)
#   --jobs <n>         Parallel make jobs (default: nproc)
#   --no-src           Skip source fetch (use existing checkout)
#   --no-build         Fetch sources only, do not build
#   --resume-from <p>  Resume build from package <p> (passed to kdesrc-build)
#   --stop-on-failure  Stop at first build failure (default: continue)
#   --dry-run          Print kdesrc-build invocation without running it
#   --help

set -uo pipefail

KPORT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
# shellcheck source=lib/kport/common.sh
source "${KPORT_ROOT}/lib/kport/common.sh"

# ── Defaults ──────────────────────────────────────────────────────────────────

CHANNEL="${KPORT_NEON_CHANNEL:-stable}"
PREFIX="${KPORT_SOURCE_BUILD_PREFIX:-/opt/kport/source-build}"
JOBS="${KPORT_BUILD_JOBS:-$(nproc 2>/dev/null || echo 4)}"
NO_SRC=false
NO_BUILD=false
RESUME_FROM=""
STOP_ON_FAILURE=false
DRY_RUN=false
PACKAGES=()

# ── Arg parsing ───────────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case "$1" in
    --channel)         CHANNEL="$2";       shift 2 ;;
    --prefix)          PREFIX="$2";        shift 2 ;;
    --jobs)            JOBS="$2";          shift 2 ;;
    --no-src)          NO_SRC=true;        shift   ;;
    --no-build)        NO_BUILD=true;      shift   ;;
    --resume-from)     RESUME_FROM="$2";   shift 2 ;;
    --stop-on-failure) STOP_ON_FAILURE=true; shift  ;;
    --dry-run)         DRY_RUN=true;       shift   ;;
    --help)
      sed -n '2,/^$/p' "$0" | grep '^#' | sed 's/^# \?//'
      exit 0
      ;;
    -*)
      kport_die "Unknown option: $1 (try --help)"
      ;;
    *)
      PACKAGES+=("$1")
      shift
      ;;
  esac
done

# ── Validate channel ──────────────────────────────────────────────────────────

case "$CHANNEL" in
  stable|unstable|nightly) ;;
  *) kport_die "Invalid channel '$CHANNEL'. Use: stable, unstable, nightly" ;;
esac

# ── Locate kdesrc-build ───────────────────────────────────────────────────────

KDESRC_BUILD=""
for candidate in \
    "${KDESRC_BUILD_CMD:-}" \
    "$(command -v kdesrc-build 2>/dev/null)" \
    "${HOME}/kde/src/kdesrc-build/kdesrc-build" \
    "/usr/bin/kdesrc-build" \
    "/usr/local/bin/kdesrc-build"; do
  if [[ -n "$candidate" && -x "$candidate" ]]; then
    KDESRC_BUILD="$candidate"
    break
  fi
done

if [[ -z "$KDESRC_BUILD" ]]; then
  kport_warn "kdesrc-build not found. Attempting to install via KDE's bootstrap script..."
  _install_kdesrc_build
fi

kport_info "Using kdesrc-build: ${KDESRC_BUILD}"

# ── Generate kdesrc-build config ──────────────────────────────────────────────

KDESRC_CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/kport/kdesrc-build"
KDESRC_CONFIG="${KDESRC_CONFIG_DIR}/kdesrc-buildrc"
KDESRC_SRC_DIR="${KPORT_SOURCE_DIR:-${HOME}/kde/src}"
KDESRC_BUILD_DIR="${KPORT_BUILD_DIR:-${HOME}/kde/build}"
KDESRC_LOG_DIR="${KPORT_LOG_DIR:-${HOME}/kde/log}"

mkdir -p "${KDESRC_CONFIG_DIR}" "${KDESRC_SRC_DIR}" "${KDESRC_BUILD_DIR}" "${KDESRC_LOG_DIR}"

_write_kdesrc_config() {
  # Map KPort channel to KDE branch group
  local branch_group
  case "$CHANNEL" in
    stable)   branch_group="kf6-qt6" ;;
    unstable) branch_group="kf6-qt6" ;;
    nightly)  branch_group="latest-qt6" ;;
  esac

  cat > "${KDESRC_CONFIG}" <<EOF
# Auto-generated by kport source-build — do not edit manually.
# Regenerated on each kport source-build invocation.

global
  branch-group  ${branch_group}
  source-dir    ${KDESRC_SRC_DIR}
  build-dir     ${KDESRC_BUILD_DIR}
  log-dir       ${KDESRC_LOG_DIR}
  install-dir   ${PREFIX}
  num-cores     ${JOBS}
  compile-commands-export true
  compile-commands-linking true

  # Use Neon's archive as the apt source for build-deps
  # (kdesrc-build --install-distro-packages reads this)
  override-build-system cmake

  cmake-options -DCMAKE_BUILD_TYPE=RelWithDebInfo \\
                -DCMAKE_INSTALL_PREFIX=${PREFIX} \\
                -DBUILD_TESTING=OFF
end global

# Include the standard KDE module set for the selected branch group.
# Individual packages specified on the command line override this.
include \${module-definitions-dir}/kf6-frameworks.ksb
include \${module-definitions-dir}/plasma.ksb
include \${module-definitions-dir}/kde-applications.ksb
EOF
  kport_info "Wrote kdesrc-build config: ${KDESRC_CONFIG}"
}

_write_kdesrc_config

# ── Apply KPort patches ───────────────────────────────────────────────────────

# After kdesrc-build fetches sources, apply any patches from the KPort
# package directory (packages/<name>/patches/*.patch).
_apply_kport_patches() {
  local pkg="$1"
  local patch_dir="${KPORT_ROOT}/packages/${pkg}/patches"
  [[ -d "$patch_dir" ]] || return 0

  local src_dir="${KDESRC_SRC_DIR}/${pkg}"
  [[ -d "$src_dir" ]] || { kport_warn "Source dir not found for ${pkg}: ${src_dir}"; return 0; }

  local patches=("${patch_dir}"/*.patch)
  [[ -e "${patches[0]}" ]] || return 0

  kport_info "Applying ${#patches[@]} KPort patch(es) to ${pkg}..."
  for patch in "${patches[@]}"; do
    kport_info "  patch: $(basename "$patch")"
    if ! git -C "$src_dir" apply --check "$patch" 2>/dev/null; then
      kport_warn "  Patch already applied or conflicts: $(basename "$patch") — skipping"
      continue
    fi
    git -C "$src_dir" apply "$patch" || kport_die "Failed to apply patch: $patch"
  done
}

# ── Build invocation ──────────────────────────────────────────────────────────

_build_packages() {
  local args=(
    "--rc-file=${KDESRC_CONFIG}"
  )

  $NO_SRC    && args+=("--no-src")
  $NO_BUILD  && args+=("--no-build")
  [[ -n "$RESUME_FROM" ]] && args+=("--resume-from=${RESUME_FROM}")
  $STOP_ON_FAILURE && args+=("--stop-on-failure")

  # Append explicit package list if provided
  if [[ ${#PACKAGES[@]} -gt 0 ]]; then
    args+=("${PACKAGES[@]}")
  fi

  kport_info "Running: ${KDESRC_BUILD} ${args[*]}"

  if $DRY_RUN; then
    echo "[dry-run] ${KDESRC_BUILD} ${args[*]}"
    return 0
  fi

  # Run kdesrc-build; capture exit code
  "${KDESRC_BUILD}" "${args[@]}"
  local rc=$?

  if [[ $rc -ne 0 ]]; then
    kport_warn "kdesrc-build exited with code ${rc}. Check logs in ${KDESRC_LOG_DIR}"
    return $rc
  fi

  kport_info "Build complete. Installed to: ${PREFIX}"
  return 0
}

# ── Patch application (post-fetch, pre-build) ─────────────────────────────────
# kdesrc-build doesn't have a native post-fetch hook, so we apply patches
# after a --no-build fetch pass, then run the build pass separately.

if [[ ${#PACKAGES[@]} -gt 0 ]] && ! $NO_SRC && ! $NO_BUILD; then
  kport_info "Fetching sources first (to allow patch application)..."
  _build_packages_fetch_only() {
    local args=(
      "--rc-file=${KDESRC_CONFIG}"
      "--no-build"
    )
    [[ -n "$RESUME_FROM" ]] && args+=("--resume-from=${RESUME_FROM}")
    [[ ${#PACKAGES[@]} -gt 0 ]] && args+=("${PACKAGES[@]}")
    $DRY_RUN && { echo "[dry-run] ${KDESRC_BUILD} ${args[*]}"; return 0; }
    "${KDESRC_BUILD}" "${args[@]}"
  }
  _build_packages_fetch_only

  for pkg in "${PACKAGES[@]}"; do
    _apply_kport_patches "$pkg"
  done

  kport_info "Building (sources already fetched)..."
  NO_SRC=true
  _build_packages
else
  _build_packages
fi

# ── Post-build: record build metadata ────────────────────────────────────────

if ! $DRY_RUN && ! $NO_BUILD; then
  METADATA_DIR="${XDG_CACHE_HOME:-${HOME}/.cache}/kport/source-builds"
  mkdir -p "$METADATA_DIR"
  METADATA_FILE="${METADATA_DIR}/last-build.json"

  python3 - <<PYEOF
import json, datetime, os, sys
pkgs = ${PACKAGES[@]+"$(IFS=','; echo "${PACKAGES[*]}")"}
pkg_list = [p.strip() for p in pkgs.split(',') if p.strip()] if pkgs else []
meta = {
    "timestamp": datetime.datetime.utcnow().isoformat() + "Z",
    "channel":   "${CHANNEL}",
    "prefix":    "${PREFIX}",
    "packages":  pkg_list,
    "jobs":      ${JOBS},
}
with open("${METADATA_FILE}", "w") as f:
    json.dump(meta, f, indent=2)
print(f"Build metadata written to ${METADATA_FILE}")
PYEOF
fi

# ── Helper: install kdesrc-build ─────────────────────────────────────────────

_install_kdesrc_build() {
  local install_dir="${HOME}/kde/src/kdesrc-build"
  if [[ ! -d "$install_dir" ]]; then
    kport_info "Cloning kdesrc-build from KDE invent..."
    git clone --depth=1 https://invent.kde.org/sdk/kdesrc-build.git "$install_dir" \
      || kport_die "Failed to clone kdesrc-build"
  fi
  KDESRC_BUILD="${install_dir}/kdesrc-build"
  chmod +x "$KDESRC_BUILD"
  kport_info "kdesrc-build installed at: ${KDESRC_BUILD}"
}
